import Head from "next/head"
import {Skills} from "../types"
import Header from "../components/Header"
import Sidebar from "../components/Sidebar"
import Section from "../components/Section"
import Experience from "../components/Experience"
import Accomplishment from "../components/Accomplishment"
import SkillCategory from "../components/SkillCategory"


 /* TODO:
 - Refactor SCSS modules to regular SCSS BEM
 - Add all content & links
 - Make sure style looks great
 - Add contact form
 - Make responsive
 - Translate with i18next
 - Animate SCSS
*/

const Index : React.FC = () => {
	return <>
		<Head>
			<title>Alexandre Fernandez</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<div id="portal"></div>
		<Header />
		<main>
			<Sidebar>
				<Section type="side" name="À PROPOS" >
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
				</Section>

				<Section type="side" name="COMPÉTENCES">
					<SkillCategory 
						name="Full stack" 
						tags={[Skills.JAVASCRIPT, Skills.TYPESCRIPT, Skills.NODEJS, Skills.NEXT, Skills.EJS, Skills.WORDPRESS]}
					/><SkillCategory 
						name="Back-end" 
						tags={[Skills.EXPRESS, Skills.MYSQL, Skills.MONGODB, Skills.MONGOOSE]}
					/><SkillCategory 
						name="Front-end" 
						tags={[Skills.REACT, Skills.REACT_NATIVE, Skills.REDUX, Skills.WEBPACK, Skills.JQUERY, Skills.HTML, Skills.CSS, Skills.SASS]}
					/><SkillCategory 
						name="Software" 
						tags={[Skills.PHOTOSHOP, Skills.ILLUSTRATOR, Skills.XD, Skills.VEGAS, Skills.UNITY, Skills.GODOT, Skills.BLENDER, Skills.WORD, Skills.EXCEL, Skills.POWERPOINT]}
					/><SkillCategory 
						name="Langues" 
						tags={[Skills.FRENCH, Skills.ENGLISH, Skills.SPANISH]}
					/><SkillCategory 
						name="Divers" 
						tags={[Skills.GIT, Skills.SEO, Skills.RESPONSIVE, Skills.API_REST, Skills.OAUTH2, Skills.MVC, Skills.BEM, Skills.CS, Skills.CPP, Skills.GDSCRIPT, Skills.PATTERNS, Skills.DATA_STRUCT]}
					/>
				</Section>
			</Sidebar>

			<div className="content">
				<Section type="main" name="EXPÉRIENCES PROFESSIONNELLES">
					<Experience 
						title="Responsable d'exploitation" 
						subtitle="CITY BUS" 
						duration="2016-2020"
					>
						<Accomplishment 
							tags={[Skills.CS, Skills.BEM, Skills.EXPRESS]}>
							Supervision du planning et gestion de ses changements en cas de	problème (véhicules en panne, retards chauffeur, etc).
						</Accomplishment><Accomplishment 
							tags={[Skills.CS, Skills.BEM, Skills.EXPRESS]}>
							Détermination des besoins en ressources humaines et en véhicules.
						</Accomplishment><Accomplishment 
							tags={[Skills.BEM]}>
							Tableaux de bords, suivi des dossiers clients, devis, saisies, etc...
						</Accomplishment>
					</Experience>
					<Experience 
						title="Superviseur en centre d’appels" 
						subtitle="Business Support Services – B2S" 
						duration="2014-2015"
					>
						<Accomplishment 
							tags={[Skills.CSS, Skills.EJS, Skills.BLENDER]}>
							Gestion de l’équipe (performances, disponibilités et incidents).
						</Accomplishment><Accomplishment 
							tags={[Skills.EJS, Skills.API_REST, Skills.CPP]}>
							Revue des performances collectives et individuelles et établissement de la stratégie coaching du mois.
						</Accomplishment><Accomplishment 
							tags={[Skills.CS, Skills.CSS]}>
							Assurer le respect des normes qualité Nissan.
						</Accomplishment>
					</Experience>
				</Section>

				<Section type="main" name="FORMATIONS">
					<Experience 
						title="Concepteur développeur d'applications - BAC +4" 
						subtitle="3W Academy" 
						duration="2022-2023"
						link="https://www.francecompetences.fr/recherche/rncp/31678/"
					>
					</Experience><Experience 
						title="Développeur intégrateur en réalisation d'applications web - BAC +2" 
						subtitle="3W Academy" 
						duration="2021-2022"
						link="https://www.francecompetences.fr/recherche/rncp/34393/"
						tags={[Skills.REACT, Skills.REACT_NATIVE, Skills.EXPRESS]}
					>
					</Experience><Experience 
						title="Autoformation informatique" 
						subtitle="Livres et internet" 
						duration="2013-2021"
						tags={[Skills.CPP, Skills.CS, Skills.GDSCRIPT]}
					>
					</Experience><Experience 
						title="Baccalauréat Scientifique" 
						subtitle="Lycée Gil y Carrasco (Espagne)" 
						duration="2011-2012"
					>
					</Experience>
				</Section>

				<Section type="main" name="PROJETS">
					<Experience 
						title="Concepteur développeur d'applications - BAC +4" 
						subtitle="3W Academy" 
						duration="2022-2023"
						
					>
					</Experience><Experience 
						title="Développeur web full stack - BAC +2" 
						subtitle="3W Academy" 
						duration="2021-2022"
						tags={[Skills.REACT, Skills.REACT_NATIVE, Skills.EXPRESS, Skills.API_REST, Skills.HTML, Skills.CSS, Skills.JAVASCRIPT, Skills.MYSQL, Skills.REDUX, Skills.RESPONSIVE]}
					>
					</Experience><Experience 
						title="Autoformation informatique" 
						subtitle="Livres et internet" 
						duration="2013-2021"
						tags={[Skills.CPP, Skills.CS, Skills.GDSCRIPT]}
					>
					</Experience><Experience 
						title="Baccalauréat Scientifique" 
						subtitle="Lycée Gil y Carrasco (Espagne)" 
						duration="2011-2012"
					>
					</Experience>
				</Section>
			</div>
		</main>
	</>
}

export default Index

/* Large screens ----------- */
/*some CSS*/

/* Desktops and laptops ----------- */
//@media only screen and (max-width : 1824px) {...}

/* iPads (landscape) ----------- */
//@media only screen and (max-width : 1224px) {...}

/* iPads (portrait) ----------- */
//@media only screen and (max-width : 1024px) {...}

/* Smartphones (landscape) ----------- */
//@media only screen and (max-width : 768px) {...}

/* Big smartphones (portrait) (ie: Galaxy 3 has 360)*/
//@media only screen and (max-width : 640px) {...}

/* Smartphones (portrait) (ie: Galaxy 1) */
//@media only screen and (max-width : 321px) {...}